### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/Users/peterngimbwa/Library/Caches/pip/wheels/80'

### ISSUE THREAD

**Issue by pngimbwa** [codekoala/django-watermark#22]
Hi, 

I am new python programmer, currently am teaching myself on how to develop python web app using Flask. 
I get the following error when i try to install bootstrap framework.

(myproject)Peters-MacBook-Pro:Flask_Application peterngimbwa$ pip install flask-bootstrap
Collecting flask-bootstrap
  Using cached Flask-Bootstrap-3.3.5.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Flask>=0.8 in ./myproject/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg (from flask-bootstrap)
Collecting dominate (from flask-bootstrap)
  Using cached dominate-2.1.12.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in ./myproject/lib/python3.4/site-packages/Werkzeug-0.10.4-py3.4.egg (from Flask>=0.8->flask-bootstrap)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in ./myproject/lib/python3.4/site-packages/Jinja2-2.8-py3.4.egg (from Flask>=0.8->flask-bootstrap)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in ./myproject/lib/python3.4/site-packages/itsdangerous-0.24-py3.4.egg (from Flask>=0.8->flask-bootstrap)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in ./myproject/lib/python3.4/site-packages/MarkupSafe-0.23-py3.4-macosx-10.6-intel.egg (from Jinja2>=2.4->Flask>=0.8->flask-bootstrap)
Building wheels for collected packages: flask-bootstrap, dominate
Exception:
Traceback (most recent call last):
  File "/Users/peterngimbwa/Documents/workspace/Flask_Application/myproject/lib/python3.4/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/Users/peterngimbwa/Documents/workspace/Flask_Application/myproject/lib/python3.4/site-packages/pip/commands/install.py", line 293, in run
    wb.build(autobuilding=True)
  File "/Users/peterngimbwa/Documents/workspace/Flask_Application/myproject/lib/python3.4/site-packages/pip/wheel.py", line 756, in build
    ensure_dir(output_dir)
  File "/Users/peterngimbwa/Documents/workspace/Flask_Application/myproject/lib/python3.4/site-packages/pip/utils/**init**.py", line 70, in ensure_dir
    os.makedirs(path)
  File "/Users/peterngimbwa/Documents/workspace/Flask_Application/myproject/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/peterngimbwa/Documents/workspace/Flask_Application/myproject/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/peterngimbwa/Documents/workspace/Flask_Application/myproject/bin/../lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/peterngimbwa/Documents/workspace/Flask_Application/myproject/bin/../lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/peterngimbwa/Library/Caches/pip/wheels/80'

The actual error is : 
PermissionError: [Errno 13] Permission denied: '/Users/peterngimbwa/Library/Caches/pip/wheels/80'

Could anyone help me to solve the error.

Thank you

Peter

**Comment by pngimbwa** [comment]
In short I get the following error when I try to install bootstrap using this command:

The command:
(myproject)Peters-MacBook-Pro:Flask_Application peterngimbwa$ pip install flask-bootstrap

Error:
PermissionError: [Errno 13] Permission denied: '/Users/peterngimbwa/Library/Caches/pip/wheels/80'

Could anyone help me to solve the problem.

Thank you

Peter

**Comment by bashu** [comment]
Check the permissions and ownerships all the way down the chain: `ls -ld /Users/peterngimbwa/Library/Caches /Users/peterngimbwa/Library/Caches/pip/ /Users/peterngimbwa/Library/Caches/pip/wheels/`. You could have done something as `root` that changed permission/ownership somewhere

**Comment by pngimbwa** [comment]
Hi Bashu, 
Thank you. I was supposed to begin with sudo when installing bootstrap.

The command was supposed to be:
$sudo pip install flask-bootstrap 

And not:
$pip install flask-bootstrap

cheers..
